name: Windows Qt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-5.9, windows-5.12]
        include:
          - name: windows-5.9
            os: windows-latest
            qt: '5.9.9'
            artifact: release/EasyGrblSetup.exe
          - name: windows-5.12
            os: windows-latest
            qt: '5.12.12'
            artifact: release/EasyGrblSetup.exe

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.29

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt }}-v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        target: 'desktop'
        tools: 'tools_openssl_x64,1.1.1-10,qt.tools.openssl.win_x64'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Create BUILD folder
      run: |
        mkdir ../build
        mkdir ../deploy
    
    - name: Build (Windows)
      working-directory: ../build
      shell: cmd
      run: |
        qmake ${{ github.workspace }}/EasyGrblSetup.pro
        nmake

    - name: Deploy (Windows)
      working-directory: ../build
      shell: cmd
      run: |
        cp ..\build\release\EasyGrblSetup.exe ..\deploy\EasyGrblSetup.exe
        windeployqt ..\deploy
        dir /S ..\deploy
        echo Test
        dir /S D:\a\TestGithubActions\Qt

    - name: Archive build result
      uses: actions/upload-artifact@v2
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/build/${{ matrix.artifact }}
