name: MacOS Qt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [macos-5.9, macos-5.12]
        include:
          - name: macos-5.9
            os: macos-latest
            qt: '5.9.9'
            artifact: EasyGrblSetup.app
          - name: macos-5.12
            os: macos-latest
            qt: '5.12.10'
            artifact: EasyGrblSetup.app

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        target: 'desktop'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Create BUILD folder
      run: |
        mkdir ../build
    
    - name: Build (MacOS)
      working-directory: ../build
      run: |
        qmake ${{ github.workspace }}/EasyGrblSetup.pro
        make
   
    - name: Archive build result
      uses: actions/upload-artifact@v2
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/build/${{ matrix.artifact }}
