name: Ubuntu Qt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        include:
          - name: ubuntu-20.04
            os: ubuntu-20.04
            artifact: EasyGrblSetup
          - name: ubuntu-22.04
            os: ubuntu-22.04
            artifact: EasyGrblSetup
          - name: ubuntu-24.04
            os: ubuntu-24.04
            artifact: EasyGrblSetup
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install qt5-default libqt5serialport5 libqt5serialport5-dev -y

    - name: Create BUILD folder
      run: |
        mkdir ../build

    - name: Build (Ubuntu)
      working-directory: ../build
      run: |
        qmake ${{ github.workspace }}/${{ matrix.artifact }}.pro
        make

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/build/${{ matrix.artifact }}
